import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import styles from "./styles/home.module.css";
import { Providers, StoreProvider } from "./providers";
import Header from "./components/header";
import ToastProvider from "./providers/ToastProvider";

const geistSans = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styles.container}`}
      >
        <StoreProvider>
          <Providers>
            <ToastProvider>
              <Header />

              <main>{children}</main>
            </ToastProvider>
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
